# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lawyer',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers_office.Office'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='records',
            field=models.ManyToManyField(to='lawyers_office.Record'),
        ),
    ]
