# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers_office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='user',
        ),
    ]
