# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers_office', '0002_remove_lawyer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=b'images')),
            ],
        ),
    ]
