# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers_office', '0003_office_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'/home/yitzhak/Downloads')),
            ],
        ),
        migrations.DeleteModel(
            name='Office_Files',
        ),
    ]
