# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers_office', '0004_auto_20161021_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFiles',
        ),
    ]
